- name: Validate variables for install.yml task
  ansible.builtin.assert:
    that:
      - docker_compose_docker_version is defined
      - docker_compose_containerd_version is defined
      - docker_compose_buildx_version is defined
      - docker_compose_version is defined

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add Docker GPG key
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  args:
    creates: /etc/apt/keyrings/docker.asc

- name: Add Docker repository
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - "docker-ce={{ docker_compose_docker_version }}"
      - "docker-ce-cli={{ docker_compose_docker_version }}"
      - "containerd.io={{ docker_compose_containerd_version }}"
      - "docker-buildx-plugin={{ docker_compose_buildx_version }}"
      - "docker-compose-plugin={{ docker_compose_version }}"
    state: present
    update_cache: true
    allow_downgrade: true

- name: Enable Docker service
  ansible.builtin.service:
    name: docker
    enabled: true

- name: Enable Containerd service
  ansible.builtin.service:
    name: containerd
    enabled: true
